runtime: nodejs20

handlers:
  # Serve all static files from the build/static directory
  - url: /static
    static_dir: build/static

  # Serve the index.html for all other routes to enable client-side routing
  - url: /.*
    static_files: build/index.html
    upload: build/index.html